<a href="<?php echo App::config("url") ?>konfiguracija/pripremaNovi" 
class=" button expanded">
<i class="fas fa-plus-square"></i>
Dodaj novog polaznika</a>

<div class="grid-container">

<form 
    action="" 
    method="get">

    <input type="text" name="uvjet" id="uvjet" 
    placeholder="unesite uvjet pretraživanja"
    value="<?php echo App::param("uvjet") ?>" />
    <input type="hidden" name="trazi" value="true" />

</form>

<div class="grid-x">
    <?php foreach($konfiguracije as $konfiguracija): ?>
        <div class="large-3 medium-6 small-12 column">
            <ul class="pricing-table">
                <li class="title"><?php echo $konfiguracija->naziv?></li>
                <li class="price"><?php echo $konfiguracija->opis?></li>
                <li class="email"><?php echo $konfiguracija->cijena?></li>
                <li>
                    <?php echo $konfiguracija->naziv?><hr />
                    <a title="Promjeni <?php echo $konfiguracija->naziv?>" 
                        href="<?php 
                        echo App::config("url") 
                        ?>konfiguracija/pripremaPromjeni/<?php echo $konfiguracija->sifra ?>">
                        <i class="fas fa-edit fa-2x" style="color: orange"></i>
                    </a>
                    <?php if($konfiguracija->ukupno==0): ?>
                        <a title="Obriši <?php echo $konfiguracija->naziv?>" 
                            onclick="return confirm('Sigurno obrisati <?php echo $konfiguracija->naziv?>');"
                            href="<?php 
                            echo App::config("url") 
                            ?>konfiguracija/brisanje/<?php echo $konfiguracija->sifra ?>">
                            <i class="fas fa-trash fa-2x" style="color: red"></i>
                        </a>
                    <?php else:?>
                        <i title="Ne može se obrisati" 
                        class="fas fa-trash fa-2x" style="color: gray"></i>
                    <?php endif;?>

                </li>
            </ul>
        </div>
    <?php endforeach;?>

</div>
</div>





