

<table id="tablicaProizvodaci">
  <thead>
    <tr>
     <th>Naziv</th>
     <th>Zemlja</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($proizvodaci as $proizvodac): ?>
      <tr>
        <td><?php echo $proizvodac->naziv?></td>
        <td><?php echo $proizvodac->zemlja?></td>
        <td>
        <a title="Promjeni <?php echo $proizvodac->naziv?>" 
            href="<?php 
            echo App::config("url") 
            ?>proizvodac/pripremaPromjeni/<?php echo $proizvodac->sifra ?>">
            <i class="fas fa-edit fa-2x" style="color: orange"></i>
        </a>
        <?php if($proizvodac->ukupno==0): ?>
            <a title="Obriši <?php echo $proizvodac->naziv?>" 
                onclick="return confirm('Sigurno obrisati <?php echo $proizvodac->naziv?>');"
                href="<?php 
                echo App::config("url") 
                ?>proizvodac/brisanje/<?php echo $proizvodac->sifra ?>">
                <i class="fas fa-trash fa-2x" style="color: red"></i>
            </a>
        <?php else:?>
            <i title="Ne može se obrisati" 
            class="fas fa-trash fa-2x" style="color: gray"></i>
        <?php endif;?>
        </td>
      </tr>
    <?php endforeach;?>
    </tbody>
</table>